#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/config/bootstrap.php';

if (!defined('YII_ENV')) {
    define('YII_ENV', env('YII_ENV', 'prod'));
}

if (!defined('YII_DEBUG')) {
    define('YII_DEBUG', (bool) env('YII_DEBUG', YII_ENV !== 'prod'));
}

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
