name: Deploy to Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to hosting via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ${{ secrets.SSH_PATH }}
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php yii migrate --interactive=0
            chmod -R 777 runtime
            chmod -R 777 web/assets
            chmod -R 777 web/uploads
            echo "Deployment completed successfully!"
